# Generated by Django 6.1 on 2026-08-28 11:03

from django.db import migrations, models


def backfill_shipped_at(apps, schema_editor):
    """Best-available estimate of ship time for orders already Shipped.

    `updated_at` is the closest signal we have for existing rows — for a terminal
    Shipped order it is almost always the moment it was moved to Shipped.
    """
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="shipped", shipped_at__isnull=True).update(shipped_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_generated_sale_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='The moment of the most recent transition into Shipped. Re-stamped if the order leaves Shipped and returns; otherwise never changes.', null=True),
        ),
        migrations.RunPython(backfill_shipped_at, migrations.RunPython.noop),
    ]
