# Generated by Django 6.1 on 2026-08-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('orders', '0002_order_generated_sale_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalert',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alerts', to='orders.order'),
        ),
    ]
