# Generated by Django 6.1 on 2026-08-28 04:51

from django.db import migrations, models


def resolve_duplicate_open_alerts(apps, schema_editor):
    """Collapse any pre-existing duplicate open alerts so AddConstraint can't fail.
    Keeps the most recent open alert per (product, order); marks the rest resolved."""
    StockAlert = apps.get_model("ai_assistant", "StockAlert")
    seen = set()
    for alert in (
        StockAlert.objects.filter(resolved=False, order__isnull=False)
        .order_by("-created_at", "-id")
    ):
        key = (alert.product_id, alert.order_id)
        if key in seen:
            alert.resolved = True
            alert.save(update_fields=["resolved"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_stockalert_order'),
        ('inventory', '0001_initial'),
        ('orders', '0002_order_generated_sale_orderitem_unit_price'),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate_open_alerts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('resolved', False)), fields=('product', 'order'), name='uniq_open_stockalert_per_product_order'),
        ),
    ]
